### ISSUE TITLE
Degrees of freedom in create_splines_model if user gives formula/basis

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#28]
If the user provides argument formula/basis to the `create_splines_model`, then the degrees of freedom argument isn't used, but the default value (4) would be put in the returned object. Not sure if this matters downstream, but seems wrong to have it as part of object. 

If the user gave both basis/formula and degrees of freedom, then object would be correct; if we put NULL for degrees of freedom if user gives either basis/formula then it would preempt the ability of the user to set that value in the returned object. 

Seems like `degrees_freedom=NULL` would work, and internally inside the function set the degrees of freedom=4 if none of the arguments was given by the user (and state that in documentation). I usually prefer having defaults in arguments so easy for user to see, but maybe in this case worthwhile.

**Comment by NelleV** [comment]
After investigation, I updated the create_meta_prediction so that it works even when the user doesn't provide the formula by raising a warning message that the smooth prediction is not possible. The fit_predict_splines (now a private method) already worked with and without the formula, as by default, it only predicts for the points used during fitting.

I'l close once #39 is merged.

**Comment by NelleV** [comment]
(The degrees of freedom in the moanin_model is set to null if the user provides the basis function or the formula and to the default (4) if the user doesn't provide anything, so that should be coherent with the user input arguments)
