### ISSUE TITLE
Function to scale centroid to the scale of the data

### ISSUE THREAD

**Issue by epurdom** [NelleV/moanin#68]
I've now added ability to overlay centroid in the `plot_splines` function, but would be more helpful if we had helper function to make spline centroid to the scale of each gene.

**Comment by NelleV** [comment]
The function I was referring to is called "align_data_onto_centroid" in R/cluster.R. It rescales the data so that it matches the centroid by finding the scaling and translation such that they minimize the mean square error (ie maximizes the likelihood of the model). In this case, we would need the "reverse", ie the scaling and translation of the centroid such that the "rescaled" centroid matches the data

**Comment by epurdom** [comment]
I see that by default, it sets negative scaling factors to zero. When we get around to fitting in with the clustering method, will need to come back to this.
